Create separate class for LogIn action
DIukhymenko/Mobiquity pull request #2
Opened 2018-08-28 20:39 UTC by DIukhymenko

Login action performing in another class.
All other tests are commented because of fail. Seems like driver initializing needs to be refactored and replaced.

2018-08-29 20:20 UTC, extsoft requested changes
@DIukhymenko In addition to comments below, please you proper formatting for your code. Next time I'll reject PR if the code is not formatted properly.

2018-08-29 20:20 UTC, extsoft commented on src/test/java/com/herokuapp/cafe/loginPage.java
> +    public void openLoginPage() {
`openLoginPage` has to open a page, but doesn't login. If you want login, you need another method which will use given credentials.

2018-08-29 20:20 UTC, extsoft commented on src/test/java/com/herokuapp/cafe/loginPage.java
> +        driver = new ChromeDriver();
This class has to aggregate `driver`. The test class has to manage driver creation. This class will use the already prepared driver.

2018-09-03 12:12 UTC, DIukhymenko commented
@extsoft 
Please review

2018-09-03 13:24 UTC, extsoft approved these changes

2018-09-03 13:27 UTC, merged